#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# xmonad directory
DIR="$HOME/.xmonad"

# Terminate if picom is already running
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
picom -b --animations --animation-window-mass 1 --animation-for-open-window zoom --animation-stiffness 200 --config "$DIR"/picom.conf &
