#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# xmonad dir
xDIR="$HOME/.xmonad"

# Export desktop session
export XDG_CURRENT_DESKTOP='xmonad'

# Kill already running process
_ps=(xsettingsd ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Launch xsettingsd daemon
xsettingsd --config="$xDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
hsetroot -cover "$xDIR"/theme/wallpaper

# Launch notification daemon
"$xDIR"/scripts/xmonad_dunst

# Launch polybar
"$xDIR"/scripts/xmonad_bar

# Launch compositor
"$xDIR"/scripts/xmonad_comp

# Start mpd
exec mpd &

# Start emacs daemon
exec emacs --daemon &

exec conky -c $HOME/.xmonad/theme/conky/conkyrc &
