## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[global/wm]
margin-bottom = 0
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

include-file = ../system.ini
include-file = ./colors.ini
include-file = ./modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; BLOCO ESQUERDO — tray + workspaces + título
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/left]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = false

width  = 30%
height = 28
offset-x = 1%
offset-y = 6

background = ${color.background}
foreground = ${color.foreground}

radius-top    = 14.0
radius-bottom = 14.0

underline-size = 0
overline-size  = 0
border-size    = 0

padding-left  = 1
padding-right = 2

module-margin-left  = 0
module-margin-right = 0

font-0 = "Iosevka Nerd Font:pixelsize=10;2"
font-1 = "Iosevka Nerd Font:bold:pixelsize=10;2"
font-2 = "SymbolsNF:pixelsize=12;2"

modules-left   = workspaces
modules-center =
modules-right  = gap title

separator  =
enable-ipc = true

[settings]
throttle-output     = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline    = over
compositing-underline   = over
compositing-border      = over
pseudo-transparency = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; BLOCO CENTRAL — VOL RAM CPU UP | música
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/center]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true

width  = 36%
height = 28
offset-x = 32%
offset-y = 6

background = ${color.background}
foreground = ${color.foreground}

radius-top    = 14.0
radius-bottom = 14.0

underline-size = 0
overline-size  = 0
border-size    = 0

padding-left  = 2
padding-right = 2

module-margin-left  = 0
module-margin-right = 0

font-0 = "Iosevka Nerd Font:pixelsize=10;2"
font-1 = "Iosevka Nerd Font:bold:pixelsize=10;2"
font-2 = "SymbolsNF:pixelsize=12;2"
font-3 = "Iosevka Nerd Font:pixelsize=13;2"

modules-left   = uptime
modules-center = vol gap2 playerctl gap player gap2 storage
modules-right  = bt-battery bluetooth

separator  =
enable-ipc = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; BLOCO DIREITO — KRN | data | shut reboot
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/right]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = false

width  = 28%
height = 28
offset-x = 71%
offset-y = 6

background = ${color.background}
foreground = ${color.foreground}

radius-top    = 14.0
radius-bottom = 14.0

underline-size = 0
overline-size  = 0
border-size    = 0

padding-left  = 2
padding-right = 2

module-margin-left  = 0
module-margin-right = 0

font-0 = "Iosevka Nerd Font:pixelsize=10;2"
font-1 = "Iosevka Nerd Font:bold:pixelsize=10;2"
font-2 = "SymbolsNF:pixelsize=12;2"
font-3 = "Iosevka Nerd Font:pixelsize=13;2"

modules-left   = kernel gap2 weather gap2 notifications
modules-center =
modules-right  =  gap audioinput gap2 datetime gap2 shutdown

separator  =
enable-ipc = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
