;; Workspaces separados por monitor
;; Monitor 1 - workspaces 1-5
[module/workspaces-1]
type = internal/xworkspaces
pin-workspaces = false
enable-click = true
enable-scroll = true
icon-default = ⭘
format = <label-state>
label-monitor = %name%

; Filtra apenas workspaces 1-5
label-active            = %icon%
label-active-foreground = #b39df3
label-active-padding    = 1

label-occupied            = %icon%
label-occupied-foreground = #9ed072
label-occupied-padding    = 1

label-urgent            = %icon%
label-urgent-foreground = #fc5d7c
label-urgent-padding    = 1

label-empty            = %icon%
label-empty-foreground = #3d4555
label-empty-padding    = 1

;; Separador entre monitores
[module/ws-sep]
type = custom/text
content = " │ "
content-foreground = #76cce0

;; Monitor 2 - workspaces 6-10
[module/workspaces-2]
type = internal/xworkspaces
pin-workspaces = false
enable-click = true
enable-scroll = true
icon-default = ⭘
format = <label-state>
label-monitor = %name%

label-active            = %icon%
label-active-foreground = #b39df3
label-active-padding    = 1

label-occupied            = %icon%
label-occupied-foreground = #9ed072
label-occupied-padding    = 1

label-urgent            = %icon%
label-urgent-foreground = #fc5d7c
label-urgent-padding    = 1

label-empty            = %icon%
label-empty-foreground = #3d4555
label-empty-padding    = 1
